#!/usr/bin/env bash
# Generate all secrets required by .env
# Usage:
#   ./scripts/gen-secrets.sh          # print to stdout
#   ./scripts/gen-secrets.sh >> .env  # append to existing .env

set -euo pipefail

rand() { openssl rand -hex 32; }

# SSH key pair (ed25519, base64-encoded OpenSSH format)
ssh_keypair() {
  local tmp; tmp=$(mktemp -u)
  ssh-keygen -t ed25519 -C "$1" -f "$tmp" -N "" -q
  base64 -w0 < "$tmp"
  rm -f "$tmp" "$tmp.pub"
}

echo "# Generated by scripts/gen-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo ""
echo "REDIS_PASSWORD=$(rand)"
echo ""
echo "DAYTONA_ENCRYPTION_KEY=$(rand)"
echo "DAYTONA_ENCRYPTION_SALT=$(rand)"
echo "DAYTONA_ADMIN_KEY=$(rand)"
echo "DAYTONA_RUNNER_API_KEY=$(rand)"
echo "DAYTONA_PROXY_API_KEY=$(rand)"
echo "DAYTONA_SSH_GATEWAY_API_KEY=$(rand)"
echo "DAYTONA_HEALTH_CHECK_API_KEY=$(rand)"
echo ""
echo "DAYTONA_SSH_GATEWAY_PRIVATE_KEY=$(ssh_keypair daytona-gateway)"
echo "DAYTONA_SSH_GATEWAY_HOST_KEY=$(ssh_keypair daytona-gateway-host)"
echo ""
echo "MINIO_ROOT_PASSWORD=$(rand)"
