// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.6
// source: internal/tee/tapp_service.proto

package tapp_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAppSecretKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	KeyType       string                 `protobuf:"bytes,2,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	X25519        bool                   `protobuf:"varint,3,opt,name=x25519,proto3" json:"x25519,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppSecretKeyRequest) Reset() {
	*x = GetAppSecretKeyRequest{}
	mi := &file_internal_tee_tapp_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppSecretKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppSecretKeyRequest) ProtoMessage() {}

func (x *GetAppSecretKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tee_tapp_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppSecretKeyRequest.ProtoReflect.Descriptor instead.
func (*GetAppSecretKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_tee_tapp_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAppSecretKeyRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetAppSecretKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *GetAppSecretKeyRequest) GetX25519() bool {
	if x != nil {
		return x.X25519
	}
	return false
}

type GetAppSecretKeyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PrivateKey      []byte                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey       []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	EthAddress      []byte                 `protobuf:"bytes,5,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	X25519PublicKey []byte                 `protobuf:"bytes,6,opt,name=x25519_public_key,json=x25519PublicKey,proto3" json:"x25519_public_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAppSecretKeyResponse) Reset() {
	*x = GetAppSecretKeyResponse{}
	mi := &file_internal_tee_tapp_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppSecretKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppSecretKeyResponse) ProtoMessage() {}

func (x *GetAppSecretKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tee_tapp_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppSecretKeyResponse.ProtoReflect.Descriptor instead.
func (*GetAppSecretKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_tee_tapp_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAppSecretKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAppSecretKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAppSecretKeyResponse) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *GetAppSecretKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *GetAppSecretKeyResponse) GetEthAddress() []byte {
	if x != nil {
		return x.EthAddress
	}
	return nil
}

func (x *GetAppSecretKeyResponse) GetX25519PublicKey() []byte {
	if x != nil {
		return x.X25519PublicKey
	}
	return nil
}

var File_internal_tee_tapp_service_proto protoreflect.FileDescriptor

const file_internal_tee_tapp_service_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/tee/tapp_service.proto\x12\ftapp_service\"b\n" +
	"\x16GetAppSecretKeyRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bkey_type\x18\x02 \x01(\tR\akeyType\x12\x16\n" +
	"\x06x25519\x18\x03 \x01(\bR\x06x25519\"\xda\x01\n" +
	"\x17GetAppSecretKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\fR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\veth_address\x18\x05 \x01(\fR\n" +
	"ethAddress\x12*\n" +
	"\x11x25519_public_key\x18\x06 \x01(\fR\x0fx25519PublicKey2m\n" +
	"\vTappService\x12^\n" +
	"\x0fGetAppSecretKey\x12$.tapp_service.GetAppSecretKeyRequest\x1a%.tapp_service.GetAppSecretKeyResponseBFZDgithub.com/0gfoundation/0g-sandbox-billing/internal/tee/tapp_serviceb\x06proto3"

var (
	file_internal_tee_tapp_service_proto_rawDescOnce sync.Once
	file_internal_tee_tapp_service_proto_rawDescData []byte
)

func file_internal_tee_tapp_service_proto_rawDescGZIP() []byte {
	file_internal_tee_tapp_service_proto_rawDescOnce.Do(func() {
		file_internal_tee_tapp_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_tee_tapp_service_proto_rawDesc), len(file_internal_tee_tapp_service_proto_rawDesc)))
	})
	return file_internal_tee_tapp_service_proto_rawDescData
}

var file_internal_tee_tapp_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_tee_tapp_service_proto_goTypes = []any{
	(*GetAppSecretKeyRequest)(nil),  // 0: tapp_service.GetAppSecretKeyRequest
	(*GetAppSecretKeyResponse)(nil), // 1: tapp_service.GetAppSecretKeyResponse
}
var file_internal_tee_tapp_service_proto_depIdxs = []int32{
	0, // 0: tapp_service.TappService.GetAppSecretKey:input_type -> tapp_service.GetAppSecretKeyRequest
	1, // 1: tapp_service.TappService.GetAppSecretKey:output_type -> tapp_service.GetAppSecretKeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_tee_tapp_service_proto_init() }
func file_internal_tee_tapp_service_proto_init() {
	if File_internal_tee_tapp_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_tee_tapp_service_proto_rawDesc), len(file_internal_tee_tapp_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_tee_tapp_service_proto_goTypes,
		DependencyIndexes: file_internal_tee_tapp_service_proto_depIdxs,
		MessageInfos:      file_internal_tee_tapp_service_proto_msgTypes,
	}.Build()
	File_internal_tee_tapp_service_proto = out.File
	file_internal_tee_tapp_service_proto_goTypes = nil
	file_internal_tee_tapp_service_proto_depIdxs = nil
}
