// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.6
// source: internal/tee/tapp_service.proto

package tapp_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TappService_GetAppSecretKey_FullMethodName = "/tapp_service.TappService/GetAppSecretKey"
)

// TappServiceClient is the client API for TappService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TappServiceClient interface {
	GetAppSecretKey(ctx context.Context, in *GetAppSecretKeyRequest, opts ...grpc.CallOption) (*GetAppSecretKeyResponse, error)
}

type tappServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTappServiceClient(cc grpc.ClientConnInterface) TappServiceClient {
	return &tappServiceClient{cc}
}

func (c *tappServiceClient) GetAppSecretKey(ctx context.Context, in *GetAppSecretKeyRequest, opts ...grpc.CallOption) (*GetAppSecretKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppSecretKeyResponse)
	err := c.cc.Invoke(ctx, TappService_GetAppSecretKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TappServiceServer is the server API for TappService service.
// All implementations must embed UnimplementedTappServiceServer
// for forward compatibility.
type TappServiceServer interface {
	GetAppSecretKey(context.Context, *GetAppSecretKeyRequest) (*GetAppSecretKeyResponse, error)
	mustEmbedUnimplementedTappServiceServer()
}

// UnimplementedTappServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTappServiceServer struct{}

func (UnimplementedTappServiceServer) GetAppSecretKey(context.Context, *GetAppSecretKeyRequest) (*GetAppSecretKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppSecretKey not implemented")
}
func (UnimplementedTappServiceServer) mustEmbedUnimplementedTappServiceServer() {}
func (UnimplementedTappServiceServer) testEmbeddedByValue()                     {}

// UnsafeTappServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TappServiceServer will
// result in compilation errors.
type UnsafeTappServiceServer interface {
	mustEmbedUnimplementedTappServiceServer()
}

func RegisterTappServiceServer(s grpc.ServiceRegistrar, srv TappServiceServer) {
	// If the following call panics, it indicates UnimplementedTappServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TappService_ServiceDesc, srv)
}

func _TappService_GetAppSecretKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppSecretKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TappServiceServer).GetAppSecretKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TappService_GetAppSecretKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TappServiceServer).GetAppSecretKey(ctx, req.(*GetAppSecretKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TappService_ServiceDesc is the grpc.ServiceDesc for TappService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TappService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tapp_service.TappService",
	HandlerType: (*TappServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppSecretKey",
			Handler:    _TappService_GetAppSecretKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/tee/tapp_service.proto",
}
